services:
  ros2_docker:
    container_name: ros2-docker
    build: ./
    volumes:
      - type: bind
        source: ${ROS_PROJECT_PATH}
        target: /home/student/ros2_ws/src/
      - ros2_workspace:/home/student/ros2_ws
    environment:
      - DISPLAY=novnc:0.0
    networks:
      - x11
    stdin_open: true
    tty: true
  novnc:
    image: theasp/novnc:latest
    environment:
      - DISPLAY_WIDTH=1920
      - DISPLAY_HEIGHT=1200
    ports:
      - "8080:8080"
    networks:
      - x11
    restart: on-failure
networks:
  x11:

volumes:
  ros2_workspace:
